apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # O servidor de produção do Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pikuhn@inf.ufpel.edu.br
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: public