apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-web-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal-web-backend
  template:
    metadata:
      labels:
        app: terminal-web-backend
    spec:
      serviceAccountName: terminal-backend-sa
      containers:
        - name: backend
          # Certifique-se que esta imagem está construída e no registro
          image: 10.220.107.110:32000/terminal-web-backend:latest 
          #image: localhost:32000/terminal-web-backend:latest 
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: terminal-web-secrets
---
# O Serviço agora é interno (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: terminal-web-service
spec:
  type: ClusterIP # MUDOU DE NodePort PARA ClusterIP
  selector:
    app: terminal-web-backend
  ports:
    - protocol: TCP
      port: 80       # Porta do Serviço (interno)
      targetPort: 3000 # Porta do Container (onde seu Node.js roda)
---
# AQUI ESTÁ A NOVIDADE: O INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terminal-web-ingress
  annotations:
    # Aumenta o tamanho máximo do corpo para uploads LTI, se necessário
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: clusterlups.inf.ufpel.edu.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terminal-web-service
            port:
              number: 80