apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal-backend-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terminal-pod-manager
rules:
  - apiGroups: [""] # "" indica a API core
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terminal-backend-binding
subjects:
  - kind: ServiceAccount
    name: terminal-backend-sa
    namespace: default # ou o namespace que estiver usando
roleRef:
  kind: Role
  name: terminal-pod-manager
  apiGroup: rbac.authorization.k8s.io